# Generated by Django 5.2.4 on 2025-08-30 00:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AVULSO', 'Avulso'), ('QUINZENAL', 'Quinzenal'), ('SEMANAL', 'Semanal')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_session_at', models.DateTimeField(blank=True, null=True)),
                ('last_session_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
