# Generated by Django 5.2.4 on 2025-08-30 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_contracts_as_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_contracts_as_therapist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.contract'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['patient'], name='appointment_patient_63a841_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['therapist'], name='appointment_therapi_d99800_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['type'], name='appointment_type_5b72c9_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['start'], name='appointment_start_3ae143_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['contract'], name='appointment_contrac_826b6d_idx'),
        ),
    ]
